
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Oliver Garces
 */
public class TecladoV extends javax.swing.JFrame {

    private ArrayList<String> pangramasList;
    private int pulsacionesCorrectas = 0;
    private int pulsacionesIncorrectas = 0;
    private String pangramaActual = "";

    public TecladoV() {
        initComponents();
        cargarPangramas();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton222 = new javax.swing.JButton();
        jButton277 = new javax.swing.JButton();
        jButton377 = new javax.swing.JButton();
        jButton477 = new javax.swing.JButton();
        jButton577 = new javax.swing.JButton();
        jButton677 = new javax.swing.JButton();
        jButton777 = new javax.swing.JButton();
        jButton877 = new javax.swing.JButton();
        jButton977 = new javax.swing.JButton();
        jButton1077 = new javax.swing.JButton();
        jButton1177 = new javax.swing.JButton();
        jButton1277 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton237 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton347 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton4277 = new javax.swing.JButton();
        jButton4377 = new javax.swing.JButton();
        jButton447 = new javax.swing.JButton();
        jButton457 = new javax.swing.JButton();
        jButton467 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton487 = new javax.swing.JButton();
        jButton497 = new javax.swing.JButton();
        jButton507 = new javax.swing.JButton();
        texto1 = new javax.swing.JTextField();
        jButton29 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton222.setBackground(new java.awt.Color(51, 51, 51));
        jButton222.setText("Esc");

        jButton277.setBackground(new java.awt.Color(51, 51, 51));
        jButton277.setText("F1");

        jButton377.setBackground(new java.awt.Color(51, 51, 51));
        jButton377.setText("F2");

        jButton477.setBackground(new java.awt.Color(51, 51, 51));
        jButton477.setText("F3");

        jButton577.setBackground(new java.awt.Color(51, 51, 51));
        jButton577.setText("F4");

        jButton677.setBackground(new java.awt.Color(51, 51, 51));
        jButton677.setText("F5");

        jButton777.setBackground(new java.awt.Color(51, 51, 51));
        jButton777.setText("F6");

        jButton877.setBackground(new java.awt.Color(51, 51, 51));
        jButton877.setText("F7");

        jButton977.setBackground(new java.awt.Color(51, 51, 51));
        jButton977.setText("F8");

        jButton1077.setBackground(new java.awt.Color(51, 51, 51));
        jButton1077.setText("F9");

        jButton1177.setBackground(new java.awt.Color(51, 51, 51));
        jButton1177.setText("F10");

        jButton1277.setBackground(new java.awt.Color(51, 51, 51));
        jButton1277.setText("TAB");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Q");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("W");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("E");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("R");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("T");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Y");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("U");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("I");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("O");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("P");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton237.setBackground(new java.awt.Color(51, 51, 51));
        jButton237.setText("MAYUS");

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("A");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("S");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("D");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(204, 204, 204));
        jButton14.setForeground(new java.awt.Color(0, 0, 0));
        jButton14.setText("F");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(204, 204, 204));
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("G");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(204, 204, 204));
        jButton16.setForeground(new java.awt.Color(0, 0, 0));
        jButton16.setText("H");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(204, 204, 204));
        jButton17.setForeground(new java.awt.Color(0, 0, 0));
        jButton17.setText("J");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("K");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setForeground(new java.awt.Color(0, 0, 0));
        jButton19.setText("L");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setForeground(new java.awt.Color(0, 0, 0));
        jButton20.setText("Ñ");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton347.setBackground(new java.awt.Color(51, 51, 51));
        jButton347.setText("SHIFT");

        jButton21.setBackground(new java.awt.Color(204, 204, 204));
        jButton21.setForeground(new java.awt.Color(0, 0, 0));
        jButton21.setText("Z");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(204, 204, 204));
        jButton22.setForeground(new java.awt.Color(0, 0, 0));
        jButton22.setText("X");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(204, 204, 204));
        jButton23.setForeground(new java.awt.Color(0, 0, 0));
        jButton23.setText("C");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(204, 204, 204));
        jButton24.setForeground(new java.awt.Color(0, 0, 0));
        jButton24.setText("V");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(204, 204, 204));
        jButton25.setForeground(new java.awt.Color(0, 0, 0));
        jButton25.setText("B");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(204, 204, 204));
        jButton26.setForeground(new java.awt.Color(0, 0, 0));
        jButton26.setText("N");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(204, 204, 204));
        jButton27.setForeground(new java.awt.Color(0, 0, 0));
        jButton27.setText("M");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton4277.setBackground(new java.awt.Color(51, 51, 51));
        jButton4277.setText(",");

        jButton4377.setBackground(new java.awt.Color(51, 51, 51));
        jButton4377.setText(".");

        jButton447.setBackground(new java.awt.Color(51, 51, 51));
        jButton447.setText("CTRL");

        jButton457.setBackground(new java.awt.Color(51, 51, 51));
        jButton457.setText("WIN");

        jButton467.setBackground(new java.awt.Color(51, 51, 51));
        jButton467.setText("ALT");

        jButton28.setBackground(new java.awt.Color(204, 204, 204));
        jButton28.setForeground(new java.awt.Color(0, 0, 0));
        jButton28.setText("SPACE");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton487.setBackground(new java.awt.Color(51, 51, 51));
        jButton487.setText("ALT");

        jButton497.setBackground(new java.awt.Color(51, 51, 51));
        jButton497.setText("CTRL");

        jButton507.setBackground(new java.awt.Color(51, 51, 51));
        jButton507.setText("ENTER");

        texto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto1KeyTyped(evt);
            }
        });

        jButton29.setBackground(new java.awt.Color(255, 102, 102));
        jButton29.setForeground(new java.awt.Color(0, 0, 0));
        jButton29.setText("INICIAR / NUEVO PANGAMA");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton347, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton237, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1277, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton222, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton447, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton277, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton457, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton467, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton377, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton487, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton497, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton477, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton577, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton677, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton777, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton877, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton977, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4277, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1077, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4377, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton507, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1177, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton277, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton377, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton477, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton577, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton677, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton777, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton877, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton977, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1077, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1177, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton222, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1277, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton237, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton347, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4277, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4377, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton507, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton497, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton447, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton457, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton467, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton487, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton4.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "R");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton1.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "Q");
// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton2.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "W");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton3.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "E");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton5.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "T");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton6.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "Y");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton7.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "U");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton8.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "I");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton9.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "O");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton10.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "P");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton11.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "A");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton12.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "S");

// EL RESTO DE TECLAS PASAN A BLANCO   
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton13.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "D");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton14.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "F");

// EL RESTO DE TECLAS PASAN A BLANCO   
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton15.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "G");

// EL RESTO DE TECLAS PASAN A BLANCO   
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton16.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "H");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton17.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "J");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton18.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "K");

// EL RESTO DE TECLAS PASAN A BLANCO    
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton19.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "L");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton20.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "Ñ");

// EL RESTO DE TECLAS PASAN A BLANCO   
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton21.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "Z");

// EL RESTO DE TECLAS PASAN A BLANCO  
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton22.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "X");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton23.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "C");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton24.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "V");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton25.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "B");

// EL RESTO DE TECLAS PASAN A BLANCO   
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton26.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "N");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton27.setBackground(Color.yellow);
texto1.setText(texto1.getText() + "M");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton28.setBackground(Color.white);
    
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
//LA TECLA SELECCIONADA PASA A MARILLO
  jButton28.setBackground(Color.yellow);
texto1.setText(texto1.getText() + " ");

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);

    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        //codigo para mostrar el pangrama en Jlabel
        
        if (!pangramasList.isEmpty()) {
            Random random = new Random();            
            int index = random.nextInt(pangramasList.size());        
            pangramaActual = pangramasList.get(index);
            jLabel1.setText(pangramaActual);    //muestra un nuevo pangrama aleatorio en Jlabel1
            
            texto1.setText("");              //borra el texto escrito por el usuario para escribir un nuevo pangrama 
            pulsacionesCorrectas = 0;        // Reinicia las pulsaciones correctas para la el nuevo pangrama
            pulsacionesIncorrectas = 0;        // Reinicia las pulsaciones incorrectas para el nuevo pangrama
            jLabel2.setText("Pulsaciones correctas: " + pulsacionesCorrectas +
                            " - Pulsaciones Incorrectas: " +pulsacionesIncorrectas);            
            
        }
        

// EL RESTO DE TECLAS PASAN A BLANCO     
    jButton1.setBackground(Color.white);
    jButton2.setBackground(Color.white);
    jButton3.setBackground(Color.white);
    jButton4.setBackground(Color.white);
    jButton5.setBackground(Color.white);
    jButton6.setBackground(Color.white);
    jButton7.setBackground(Color.white);
    jButton8.setBackground(Color.white);
    jButton9.setBackground(Color.white);
    jButton10.setBackground(Color.white);
    jButton11.setBackground(Color.white);
    jButton12.setBackground(Color.white);
    jButton13.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton14.setBackground(Color.white);
    jButton15.setBackground(Color.white);
    jButton16.setBackground(Color.white);
    jButton17.setBackground(Color.white);
    jButton18.setBackground(Color.white);
    jButton19.setBackground(Color.white);
    jButton20.setBackground(Color.white);
    jButton21.setBackground(Color.white);
    jButton22.setBackground(Color.white);
    jButton23.setBackground(Color.white);
    jButton24.setBackground(Color.white);
    jButton25.setBackground(Color.white);
    jButton26.setBackground(Color.white);
    jButton27.setBackground(Color.white);
    jButton28.setBackground(Color.white);

    }//GEN-LAST:event_jButton29ActionPerformed

    private void texto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto1KeyTyped
        
        
        // Se obtiene la tecla ingresada por el usuario y la tecla esperada del pangrama actual
        if (!pangramaActual.isEmpty()) { 
            char teclaIngresada = evt.getKeyChar();  
            char teclaEsperada = pangramaActual.charAt(pulsacionesCorrectas);
            
            //Compara la tecla ingresada con la tecla esperada e incrementamos las pulsaciones correctas si la tecla coincide
            // asi mismo incrementa las pulsaciones incorrectras si no coinciden 
            
            if (teclaIngresada == teclaEsperada) {   
                pulsacionesCorrectas++;            
                
            }else {
                pulsacionesIncorrectas++;      
                
            }
            
            jLabel2.setText("Pulsaciones correctas: " + pulsacionesCorrectas +
                            " - Pulsaciones incorrectas: " + pulsacionesIncorrectas);
        }
    }//GEN-LAST:event_texto1KeyTyped
   
    //buscamos el acrchivo de texto en donde se encuentran los pangramas y se muestran en pantalla
    
    private void cargarPangramas() {
      pangramasList = new ArrayList<>();
        
        try {
            BufferedReader reader = new BufferedReader(new FileReader("D:\\Oliver\\UTM\\POO\\pangramas.txt"));
            String line;
            while ((line = reader.readLine()) != null) {
                pangramasList.add(line);
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TecladoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TecladoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TecladoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TecladoV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TecladoV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton1077;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton1177;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton1277;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton237;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton277;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton347;
    private javax.swing.JButton jButton377;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton4277;
    private javax.swing.JButton jButton4377;
    private javax.swing.JButton jButton447;
    private javax.swing.JButton jButton457;
    private javax.swing.JButton jButton467;
    private javax.swing.JButton jButton477;
    private javax.swing.JButton jButton487;
    private javax.swing.JButton jButton497;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton507;
    private javax.swing.JButton jButton577;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton677;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton777;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton877;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton977;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField texto1;
    // End of variables declaration//GEN-END:variables
}
